name: calculate-ci-job
on:  
  push:
    branches-ignore: [ master ]
  pull_request:   
    branches-ignore: [ master ]
  schedule: 
    - cron:  '0 1 * * *'
       
jobs: 
  build-jdk8:
    runs-on: ${{ matrix.os }}
    strategy:
     max-parallel: 3
     fail-fast: false
     #GitHub-hosted runners, possible to add: windows-latest
     matrix:
       os: [ubuntu-latest]
          
    name: calculate-ci-job
    steps:
    - name: Checkout
      uses: actions/checkout@v1
         
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1
      env:
        JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
        M2_HOME: /usr/local/apache-maven/apache-maven-3.6.3 
        
    - name: Ping JFrog CLI
      run: jfrog rt ping

    - name: Set Environment Variables
      run: |
        echo "::set-env name=repository::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
        echo $repository

    # if pushed from a feature branch, should create a proper repository in artifactory for that  
    - name: Feature Branch Repository Creation
      run: |
        jfrog rt rc templates/local-repo-template.json --vars key1=$repository
        jfrog rt rc templates/remote-repo-template.json --vars key1=$repository
        jfrog rt rc templates/virtual-repo-template.json --vars key1=$repository
  
    - if: always()   
      name: Feature Branch Repository Update
      env:
        SERVER_ID: tal-eplus-saas
      run: |
        echo "::set-env name=repository::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
        jfrog rt mvnc --server-id-resolve=$SERVER_ID --server-id-deploy=$SERVER_ID --repo-resolve-releases=auto-cli-virtual-$repository --repo-resolve-snapshots=auto-cli-virtual-$repository --repo-deploy-releases=auto-cli-virtual-$repository --repo-deploy-snapshots=auto-cli-virtual-$repository
     
    - if: always()
      name: Build & Deploy
      run: | 
        cd maths && jfrog rt mvn clean install
        
    - if: always() 
      name: Publish Build Information
      run: |
        # Collect environment variables for the build
        jfrog rt bce
        # Collect VCS details from git and add them to the build
        jfrog rt bag
        # Publish build info
        jfrog rt bp       
        
    - if: always()
      name: Xray Scan
      run: |
        jfrog rt bs

    - if: always()
      name: Feature Branch Repository Deletion
      env:
        NUMBER_OF_DAYS_TO_KEEP: 90
      run: |
        # Extract all the LOCAL repositories created automatically by the CI process
        jfrog rt curl -XGET /api/repositories | jq '[.[] | .key | select(test("auto-cli-local"))]' > deletion/auto_created_repositories.json && cat deletion/auto_created_repositories.json

        # Calculate for which month are we going back to verify who should be deleted
        jq -n 'now - 3600 * 24 * '$NUMBER_OF_DAYS_TO_KEEP' | gmtime | todate' > deletion/months_indicator && cat deletion/months_indicator

        # Iterate over all the repositories, delete those by the latest file that was modified
        jq -c '.[]' deletion/auto_created_repositories.json | while read i; do
          echo Iterating repository = $i
          sh -c "jfrog rt s --spec deletion/repositories-spec.json --spec-vars='key1="$i"' > deletion/search_results && cat deletion/search_results"
          
          # If the repository is empty / latest modified file is older > NUMBER_OF_DAYS_TO_KEEP days => DELETE the repository
          if [[ $(cat deletion/search_results) == "[]" ]]; then
             echo "Deleting repository: $i, repository is empty"
             sh -c "jfrog rt rdel $i --quiet && jfrog rt rdel ${i//local/virtual} --quiet && jfrog rt rdel ${i//local/jcenter} --quiet"
          elif [[ $(cat deletion/search_results | jq --arg month_indicator $(cat deletion/months_indicator) '.[] | .modified | . <= $month_indicator') = "true" ]]; then             
             echo "Deleting repository: $i, too old to keep in Artifactory"
             sh -c "jfrog rt rdel $i --quiet && jfrog rt rdel ${i//local/virtual} --quiet && jfrog rt rdel ${i//local/jcenter} --quiet"
          else
             echo "Skipping Repository deletion - repository is still relevant"
          fi
        done        